image: python:3.9

stages:
  - run-calendar

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

run-calendar:
  stage: run-calendar
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
    # Create directories
    - mkdir -p credentials
    # Create environment files
    - echo "$API_FOOTBALL_KEY" > .env
    - echo "$FOOTBALL_DATA_API_KEY" >> .env
    - echo "$RECIPIENT_EMAIL" >> .env
    # Create Google credentials files
    - echo "$GOOGLE_CALENDAR_CREDENTIALS" > credentials/credentials.json
    - echo "$GOOGLE_CALENDAR_TOKEN" > credentials/token.json
    # Run scripts
    - python fetch_matches.py
    - python fetch_tv_schedule.py
    - python send_calendar_email.py
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
