[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python fetch_matches.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[schedule]
cron = ["0 6,12,18 * * *"]  # Run at 6:00, 12:00, and 18:00 Rome time
