name: Daily Football Matches Calendar

on:
  schedule:
    - cron: '0 11 * * *'  # Run at 11:00 UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  update_calendar:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot==20.7
        pip install google-api-python-client
        pip install google-auth-httplib2
        pip install google-auth-oauthlib
        pip install icalendar==5.0.11
        pip install python-dotenv
        pip install pytz==2023.3
        pip install requests
        pip install beautifulsoup4==4.12.2
    
    - name: Set up environment
      env:
        GOOGLE_CALENDAR_TOKEN: ${{ secrets.GOOGLE_CALENDAR_TOKEN }}
        API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        mkdir -p credentials
        echo "$GOOGLE_CALENDAR_TOKEN" > credentials/token.json
        echo "API_FOOTBALL_KEY=$API_FOOTBALL_KEY" > .env
        echo "FOOTBALL_DATA_API_KEY=$FOOTBALL_DATA_API_KEY" >> .env
        echo "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN" >> .env
    
    - name: Run script
      run: python fetch_matches.py
