name: Daily Football Notifications

on:
  schedule:
    - cron: '0 5,11,17 * * *'  # Runs at 6:00, 12:00, and 18:00 Rome time (UTC+1)
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    env:
      TZ: 'Europe/Rome'  # Set timezone to Rome
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run notification script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python fetch_matches.py
